---
language: go
go:
- 1.3.3
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
before_install:
- go get github.com/meatballhat/deppy
- go get github.com/golang/lint/golint
- go get code.google.com/p/go.tools/cmd/cover
# - go install -a -race std
