sudo: false
language: go
go:
- 1.3.3
env:
  global:
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"
  - REDIS_PORT=16379
  - REDIS_URL="redis://localhost:$REDIS_PORT/0"
before_install:
- go get github.com/hamfist/deppy
- go get github.com/golang/lint/golint
- go get code.google.com/p/go.tools/cmd/cover
install:
- deppy restore
before_script:
- redis-server --port 16379 > redis-server.log 2>&1 &
- echo $! > redis-server.pid
script:
- go get -x -v ./...
- go test -v ./...
- ~/gopath/bin/worker-manager-service >> server.log 2>&1 &
- for r in 0 1 2 3 4 ; do
  ./bin/test-request instance-build ;
  done
- redis-cli -r 5 --raw -p "$REDIS_PORT" RPOP "worker-manager:queue:instance-builds" |
    while read line ; do echo $line | python -m json.tool ; done
- kill "$(cat redis-server.pid)"
- ./bin/test-request shutdown
after_script:
- cat server.log
